
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author win
 */
public class CadRemedioMani extends javax.swing.JFrame {
    private Medmanipulado remmani;
    private GerPro gerpro = new GerPro();
    
    /**
     * Creates new form CadRemedioMani
     */
    public CadRemedioMani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        cxpublico = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cxsintomas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cxvalidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cxdisp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cxcodigo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cxpeso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cxpreco = new javax.swing.JTextField();
        cxnome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cxnomeclinico = new javax.swing.JTextField();
        cxnomecli = new javax.swing.JLabel();
        cxcomposicao = new javax.swing.JTextField();
        BtSair = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cxperiodo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cxnomepaci = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cxcpf = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cxativo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cxformula = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cxcrm = new javax.swing.JTextField();
        BtLimpar = new javax.swing.JButton();
        BtCadastrar = new javax.swing.JButton();
        BtConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setText("Publico Alvo:");

        cxpublico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxpublicoActionPerformed(evt);
            }
        });

        jLabel7.setText("Sintomas Recomendados:");

        cxsintomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxsintomasActionPerformed(evt);
            }
        });

        jLabel8.setText("Validade (coloque na forma xxx/xx/xxxx):");

        cxvalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxvalidadeActionPerformed(evt);
            }
        });

        jLabel9.setText("Disponibilidade:");

        cxdisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxdispActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(204, 0, 51));
        jLabel10.setText("Codigo de Barra:");

        cxcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxcodigoActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(204, 0, 51));
        jLabel11.setText("Miligramas (apenas números):");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro Medicamento Manipulado:");

        cxpeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxpesoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel12.setForeground(new java.awt.Color(204, 0, 51));
        jLabel12.setText("Preço:");

        cxpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxprecoActionPerformed(evt);
            }
        });

        cxnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxnomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome Clinico:");

        cxnomeclinico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxnomeclinicoActionPerformed(evt);
            }
        });

        cxnomecli.setText("Composição:");

        cxcomposicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxcomposicaoActionPerformed(evt);
            }
        });

        BtSair.setText("Voltar");
        BtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSairActionPerformed(evt);
            }
        });

        jLabel5.setText("Periodo de Uso:");

        cxperiodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxperiodoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Dados do Paciente:");

        jLabel14.setText("Nome do Paciente");

        cxnomepaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxnomepaciActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(204, 0, 51));
        jLabel15.setText("CPF do Cliente:");

        cxcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxcpfActionPerformed(evt);
            }
        });

        jLabel16.setText("Componente Ativo:");

        cxativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxativoActionPerformed(evt);
            }
        });

        jLabel17.setText("Formula:");

        cxformula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxformulaActionPerformed(evt);
            }
        });

        jLabel18.setText("CRM do Medico:");

        cxcrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxcrmActionPerformed(evt);
            }
        });

        BtLimpar.setText("Limpar");
        BtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLimparActionPerformed(evt);
            }
        });

        BtCadastrar.setText("Cadastrar");
        BtCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadastrarActionPerformed(evt);
            }
        });

        BtConsultar.setText("Consultar Codigo de Barra");
        BtConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxnomeclinico))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cxnomecli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxcomposicao))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxperiodo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxpublico))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxsintomas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxvalidade))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxdisp))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxcodigo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxpeso))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxpreco))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxnome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxnomepaci, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxformula))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxcpf))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxcrm))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxativo))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtLimpar)
                                .addGap(18, 18, 18)
                                .addComponent(BtSair))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtCadastrar)
                                .addGap(18, 18, 18)
                                .addComponent(BtConsultar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cxnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cxnomeclinico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cxnomecli)
                            .addComponent(cxcomposicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cxperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cxpublico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cxsintomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cxvalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cxnomepaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cxcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(cxativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(cxformula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(cxcrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cxdisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cxcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cxpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cxpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtCadastrar)
                    .addComponent(BtConsultar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtSair)
                    .addComponent(BtLimpar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxpublicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxpublicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxpublicoActionPerformed

    private void cxsintomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxsintomasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxsintomasActionPerformed

    private void cxvalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxvalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxvalidadeActionPerformed

    private void cxdispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxdispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxdispActionPerformed

    private void cxcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxcodigoActionPerformed

    private void cxpesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxpesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxpesoActionPerformed

    private void cxprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxprecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxprecoActionPerformed

    private void cxnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxnomeActionPerformed

    private void cxnomeclinicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxnomeclinicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxnomeclinicoActionPerformed

    private void cxcomposicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxcomposicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxcomposicaoActionPerformed

    private void BtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSairActionPerformed
        sair();
    }//GEN-LAST:event_BtSairActionPerformed
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null,"Deseja Realmente Sair?","Saída",JOptionPane.YES_NO_OPTION);
        if(resp== 0) this.dispose();
    }
    
    private void cxperiodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxperiodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxperiodoActionPerformed

    private void cxnomepaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxnomepaciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxnomepaciActionPerformed

    private void cxcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxcpfActionPerformed

    private void cxativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxativoActionPerformed

    private void cxformulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxformulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxformulaActionPerformed

    private void cxcrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxcrmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxcrmActionPerformed

    private void BtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLimparActionPerformed
        limpar();
    }//GEN-LAST:event_BtLimparActionPerformed

    
    private void limpar(){
        cxnome.setText("");
        cxnomeclinico.setText("");
        cxcomposicao.setText("");
        cxperiodo.setText("");
        cxpublico.setText("");
        cxsintomas.setText("");
        cxvalidade.setText("");
        cxdisp.setText("");
        cxcodigo.setText("");
        cxpeso.setText("");
        cxpreco.setText("");
        cxnomepaci.setText("");
        cxcpf.setText("");
        cxativo.setText("");
        cxformula.setText("");
        cxcrm.setText("");
    }

    private void BtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadastrarActionPerformed
        cadastrar();
       //listtabela();
    }//GEN-LAST:event_BtCadastrarActionPerformed

    public void cadastrar(){
    
    remmani = new Medmanipulado();
    try{
    remmani = (Medmanipulado) gerpro.cadPro(remmani);
        
    remmani.setNome(cxnome.getText());
    remmani.setNomeClinico(cxnomeclinico.getText());
    remmani.setComposicao(cxcomposicao.getText());
    remmani.setPeriodoUso(cxperiodo.getText());
    remmani.setPublicoAlvo(cxpublico.getText());
    remmani.setSitRecomenda(cxsintomas.getText());
    remmani.setValidade(cxvalidade.getText());
    remmani.setDisponibilidade(cxdisp.getText());
    
    remmani.setCodigoBarra(Integer.parseInt(cxcodigo.getText()));
    remmani.setMiligramas(Integer.parseInt(cxpeso.getText()));
    remmani.setPreco(Integer.parseInt(cxpreco.getText()));
    
    remmani.setNomecliente(cxnomepaci.getText());
    remmani.setCpf(Integer.parseInt(cxcpf.getText()));
    remmani.setAtivo(cxativo.getText());
    remmani.setFormula(cxformula.getText());
    remmani.setCRM(cxcrm.getText());
    
        if(remmani != null){JOptionPane.showMessageDialog(null,"Produto cadastrado!","Cadastro", 1);} 
        limpar();
    
    }catch(NumberFormatException nfe){
        JOptionPane.showMessageDialog(null,"coloque apenas numeros inteiros\nonde estiver em vermelho!","ERRO NA ENTRADA!", 0);
     
    }
    }
    
    private void BtConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConsultarActionPerformed
        consultar();
    }//GEN-LAST:event_BtConsultarActionPerformed
    
    public void consultar(){
        remmani = new Medmanipulado();
        
        try{
        remmani.setCodigoBarra(Integer.parseInt(cxcodigo.getText()));
        
        remmani = (Medmanipulado) gerpro.consProCod(remmani);
        
        if(remmani != null){
            cxcodigo.setText(Integer.toString((int) remmani.getCodigoBarra()));
            cxpeso.setText(Integer.toString((int) remmani.getMiligramas()));
            cxpreco.setText(Integer.toString((int) remmani.getPreco()));
            
            cxnome.setText(remmani.getNome());
            cxnomeclinico.setText(remmani.getNomeClinico());
            cxcomposicao.setText(remmani.getComposicao());
            cxperiodo.setText(remmani.getPeriodoUso());
            cxpublico.setText(remmani.getPublicoAlvo());
            cxsintomas.setText(remmani.getSitRecomenda());
            cxvalidade.setText(remmani.getValidade());
            cxdisp.setText(remmani.getDisponibilidade());
            
            cxnomepaci.setText(remmani.getNomeCliente());
            cxcpf.setText(Integer.toString((int) remmani.getCPF()));
            cxativo.setText(remmani.getAtivo());
            cxformula.setText(remmani.getFormula());
            cxcrm.setText(remmani.getCRM());
                
            
        
            JOptionPane.showMessageDialog(null,"Confirme os dados","Confimação",1);
            limpar();
        }else{
            JOptionPane.showMessageDialog(null,"Não existe produto com esse codigo","Codigo Inexistente",1);
            limpar();
        
        }}catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(null,"O Codigo de Barra deve ser um número inteiro!","Erro de Busca",0);
                cxcodigo.setText("");
            
                }
    }
    
    
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadRemedioMani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadRemedioMani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadRemedioMani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadRemedioMani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadRemedioMani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCadastrar;
    private javax.swing.JButton BtConsultar;
    private javax.swing.JButton BtLimpar;
    private javax.swing.JButton BtSair;
    private javax.swing.JTextField cxativo;
    private javax.swing.JTextField cxcodigo;
    private javax.swing.JTextField cxcomposicao;
    private javax.swing.JTextField cxcpf;
    private javax.swing.JTextField cxcrm;
    private javax.swing.JTextField cxdisp;
    private javax.swing.JTextField cxformula;
    private javax.swing.JTextField cxnome;
    private javax.swing.JLabel cxnomecli;
    private javax.swing.JTextField cxnomeclinico;
    private javax.swing.JTextField cxnomepaci;
    private javax.swing.JTextField cxperiodo;
    private javax.swing.JTextField cxpeso;
    private javax.swing.JTextField cxpreco;
    private javax.swing.JTextField cxpublico;
    private javax.swing.JTextField cxsintomas;
    private javax.swing.JTextField cxvalidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
