//Nome: Stefano Calheiros Stringhini - RA: 2312123

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author win
 */
public class CadOutros extends javax.swing.JFrame {
    private Outros produto;
    private GerPro gerpro = new GerPro();
    
    /**
     * Creates new form CadOutros
     */
    public CadOutros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        cxvalidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cxdisp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cxcodigo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cxpeso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cxpreco = new javax.swing.JTextField();
        cxnome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cxtipo = new javax.swing.JTextField();
        BtSair = new javax.swing.JButton();
        BtCadastrar1 = new javax.swing.JButton();
        BtConsultar = new javax.swing.JButton();
        BtAlterar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        BtLimpar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblMed = new javax.swing.JTable();
        BtDesconto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setText("Validade (coloque na forma xxx/xx/xxxx):");

        cxvalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxvalidadeActionPerformed(evt);
            }
        });

        jLabel9.setText("Disponibilidade:");

        cxdisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxdispActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(204, 0, 51));
        jLabel10.setText("Codigo de Barra:");

        cxcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxcodigoActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(204, 0, 51));
        jLabel11.setText("Peso (em gramas):");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Produtos:");

        cxpeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxpesoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel12.setForeground(new java.awt.Color(204, 0, 51));
        jLabel12.setText("Preço:");

        cxpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxprecoActionPerformed(evt);
            }
        });

        cxnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxnomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo:");

        cxtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxtipoActionPerformed(evt);
            }
        });

        BtSair.setText("Voltar");
        BtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSairActionPerformed(evt);
            }
        });

        BtCadastrar1.setText("Cadastrar");
        BtCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadastrar1ActionPerformed(evt);
            }
        });

        BtConsultar.setText("Consultar Codigo de Barra");
        BtConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConsultarActionPerformed(evt);
            }
        });

        BtAlterar.setText("Alterar pelo Codigo de Barra");
        BtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlterarActionPerformed(evt);
            }
        });

        BtExcluir.setText("Excluir pelo Codigo de Barra");
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });

        BtLimpar.setText("Limpar");
        BtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLimparActionPerformed(evt);
            }
        });

        TblMed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo de Barra", "Nome", "Validade", "Preço"
            }
        ));
        jScrollPane2.setViewportView(TblMed);

        BtDesconto.setText("Desconto");
        BtDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDescontoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxdisp))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxtipo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxvalidade))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxpeso))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxpreco))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxnome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxcodigo)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(BtSair))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtCadastrar1)
                        .addGap(18, 18, 18)
                        .addComponent(BtConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(BtAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(BtExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(BtDesconto)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cxnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cxtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cxvalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cxdisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cxcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cxpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cxpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtCadastrar1)
                    .addComponent(BtConsultar)
                    .addComponent(BtAlterar)
                    .addComponent(BtExcluir)
                    .addComponent(BtDesconto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtSair)
                    .addComponent(BtLimpar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxvalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxvalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxvalidadeActionPerformed

    private void cxdispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxdispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxdispActionPerformed

    private void cxcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxcodigoActionPerformed

    private void cxpesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxpesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxpesoActionPerformed

    private void cxprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxprecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxprecoActionPerformed

    private void cxnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxnomeActionPerformed

    private void cxtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxtipoActionPerformed

    private void BtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSairActionPerformed
        sair();
    }//GEN-LAST:event_BtSairActionPerformed

    private void BtCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadastrar1ActionPerformed
        cadastrar();
        listtabela();
    }//GEN-LAST:event_BtCadastrar1ActionPerformed

    private void BtConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConsultarActionPerformed
        consultar();
    }//GEN-LAST:event_BtConsultarActionPerformed

    private void BtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlterarActionPerformed
        alterar();
        listtabela();
        limpar();
    }//GEN-LAST:event_BtAlterarActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        excluir();
        listtabela();
        limpar();
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void BtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLimparActionPerformed
        limpar();
    }//GEN-LAST:event_BtLimparActionPerformed

    private void BtDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDescontoActionPerformed
        desconto();
    }//GEN-LAST:event_BtDescontoActionPerformed
    
    public void desconto(){
     produto = new Outros();
     try{
        produto.setCodigoBarra(Integer.parseInt(cxcodigo.getText()));
        
        produto = (Outros) gerpro.consProCod(produto);
        
        if(produto != null){
            cxpreco.setText(Integer.toString((int) produto.getPreco()));
            
            JOptionPane.showMessageDialog(null,"Preço com Desconto: " +produto.desconto(),"Desconto",1);
            limpar();
        }else{
            JOptionPane.showMessageDialog(null,"Não existe produto com esse codigo","Codigo Inexistente",1);
            limpar();
        
        }}catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(null,"O Codigo de Barra deve ser um número inteiro!","Erro de Busca",0);
                cxcodigo.setText("");}
    
    }
    
    private void limpar(){
        cxnome.setText("");
        cxtipo.setText("");
        cxvalidade.setText("");
        cxdisp.setText("");
        cxcodigo.setText("");
        cxpeso.setText("");
        cxpreco.setText("");
    }
    
    public void excluir(){
        produto = new Outros();

            try{
            produto.setCodigoBarra(Integer.parseInt(cxcodigo.getText()));

            produto = (Outros) gerpro.consProCod(produto);

            if(produto != null){
                cxcodigo.setText(Integer.toString((int) produto.getCodigoBarra()));
                cxpeso.setText(Integer.toString((int) produto.getPeso()));
                cxpreco.setText(Integer.toString((int) produto.getPreco()));
                
                cxtipo.setText(produto.getTipo());
                cxnome.setText(produto.getNome());
                cxvalidade.setText(produto.getValidade());
                cxdisp.setText(produto.getDisponibilidade());
                int x = JOptionPane.showConfirmDialog(null,"Deseja realmente excluir?","Confirmação de Exclusão",JOptionPane.YES_NO_OPTION);
                    if(x==0){ 
                    gerpro.removeProCod(produto);
                    JOptionPane.showMessageDialog(null,"Produto excluido com sucesso!","Exclusão concluida",1);
                    }

            }else{
                JOptionPane.showMessageDialog(null,"Não existe produto com esse codigo","Codigo Inexistente",1);
                limpar();

            }}catch(NumberFormatException nfe){
                    JOptionPane.showMessageDialog(null,"O Codigo de Barra deve ser um número inteiro!","Erro de Busca",0);
                    cxcodigo.setText("");

                    }
 
    }
    
    public void alterar(){
        produto = new Outros();

            try{
            produto.setCodigoBarra(Integer.parseInt(cxcodigo.getText()));

            produto = (Outros) gerpro.atualizaProCod(produto);

            if(produto != null){
                cxcodigo.setText(Integer.toString((int) produto.getCodigoBarra()));
                cxpeso.setText(Integer.toString((int) produto.getPeso()));
                cxpreco.setText(Integer.toString((int) produto.getPreco()));
                cxtipo.setText(produto.getTipo());
                cxnome.setText(produto.getNome());
                cxvalidade.setText(produto.getValidade());
                cxdisp.setText(produto.getDisponibilidade());
                JOptionPane.showMessageDialog(null,"Dados Atualizados!","Atualização de Dados",1);
                limpar();
            }else{
                JOptionPane.showMessageDialog(null,"Não existe produto com esse codigo","Codigo Inexistente",1);
                limpar();

            }}catch(NumberFormatException nfe){
                    JOptionPane.showMessageDialog(null,"O Codigo de Barra deve ser um número inteiro!","Erro de Busca",0);
                    cxcodigo.setText("");

                    }
    
    
    
    
    }
    
    public void consultar(){
        produto = new Outros();
        
        try{
        produto.setCodigoBarra(Integer.parseInt(cxcodigo.getText()));
        
        produto = (Outros) gerpro.consProCod(produto);
        
        if(produto != null){
            cxcodigo.setText(Integer.toString((int) produto.getCodigoBarra()));
            cxpreco.setText(Integer.toString((int) produto.getPreco()));
            cxpeso.setText(Integer.toString((int) produto.getPeso()));
            cxnome.setText(produto.getNome());
            cxvalidade.setText(produto.getValidade());
            cxdisp.setText(produto.getDisponibilidade());
            cxtipo.setText(produto.getTipo());
            JOptionPane.showMessageDialog(null,"Confirme os dados","Confimação",1);
            limpar();
        }else{
            JOptionPane.showMessageDialog(null,"Não existe produto com esse codigo","Codigo Inexistente",1);
            limpar();
        
        }}catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(null,"O Codigo de Barra deve ser um número inteiro!","Erro de Busca",0);
                cxcodigo.setText("");
            
                }
    }
    
    public void listtabela(){
    DefaultTableModel modelo = (DefaultTableModel) TblMed.getModel();   
     int poslin = 0;
    
    modelo.setRowCount(poslin);
    
        for(Outros rem : gerpro.getBdPro()){
            modelo.insertRow(poslin, new Object []{rem.getCodigoBarra(),rem.getNome(),rem.getValidade(),rem.getPreco()});
            poslin++;

        }}
     
            
    public void cadastrar(){
    
    produto = new Outros();
    try{
        
    produto.setNome(cxnome.getText());
    produto.setValidade(cxvalidade.getText());
    produto.setDisponibilidade(cxdisp.getText());
    
    produto.setCodigoBarra(Integer.parseInt(cxcodigo.getText()));
    produto.setPeso(Integer.parseInt(cxpeso.getText()));
    produto.setPreco(Integer.parseInt(cxpreco.getText()));
    
    produto = (Outros) gerpro.cadPro(produto);
    
        if(produto != null){JOptionPane.showMessageDialog(null,"Produto cadastrado!","Cadastro", 1);} 
        limpar();
    
    }catch(NumberFormatException nfe){
        JOptionPane.showMessageDialog(null,"coloque apenas numeros inteiros\nonde estiver em vermelho!","ERRO NA ENTRADA!", 0);
        
    }
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null,"Deseja Realmente Sair?","Saída",JOptionPane.YES_NO_OPTION);
        if(resp== 0) this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadOutros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadOutros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadOutros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadOutros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadOutros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlterar;
    private javax.swing.JButton BtCadastrar1;
    private javax.swing.JButton BtConsultar;
    private javax.swing.JButton BtDesconto;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtLimpar;
    private javax.swing.JButton BtSair;
    private javax.swing.JTable TblMed;
    private javax.swing.JTextField cxcodigo;
    private javax.swing.JTextField cxdisp;
    private javax.swing.JTextField cxnome;
    private javax.swing.JTextField cxpeso;
    private javax.swing.JTextField cxpreco;
    private javax.swing.JTextField cxtipo;
    private javax.swing.JTextField cxvalidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
